# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  name: da_ponderosa
  latitude: !secret lat
  longitude: !secret long
  elevation: 1939
  unit_system: imperial
  country: US
  time_zone: America/Denver
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
#template: !include template.yaml
input_select:
media_source:
mobile_app:
my:
sun:
usb:
zha_toolkit:
bluetooth:
color_extractor:
conversation:
# binary_sensor: !include binary_sensor.yaml

#logger:

http:
  server_port: 2083
  use_x_forwarded_for: true
  trusted_proxies:
  - 173.245.48.0/20
  - 103.21.244.0/22
  - 103.22.200.0/22
  - 103.31.4.0/22
  - 141.101.64.0/18
  - 108.162.192.0/18
  - 190.93.240.0/20
  - 188.114.96.0/20
  - 197.234.240.0/22
  - 198.41.128.0/17
  - 162.158.0.0/15
  - 104.16.0.0/13
  - 104.24.0.0/14
  - 172.64.0.0/13
  - 131.0.72.0/22
  - 172.30.33.0/24
  - 198.41.192.7
  - 198.41.200.63
  - 198.41.192.37
  - 192.168.111.93
  login_attempts_threshold: 5
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


#Device Tracker
device_tracker:
  - platform: bluetooth_le_tracker
  
#Frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: 
    - /www/community/lovelace-card-mod/card-mod.js
  
recorder:
  auto_purge: true
  auto_repack: true

# Text to speech
tts:
  - platform: google_translate

#Integrations
#Notify
notify_events:
  token: !secret notify_token

notify:
  - platform: notify_events
    name: "watchman"
  - platform: html5
    vapid_pub_key: !secret pub_key
    vapid_prv_key: !secret prv_key
    vapid_email: !secret vemail

#Influx DB
#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: !secret influxdb_user
#  password: !secret influxdb_pw
#  max_retries: 3
#  default_measurement: state

#wemo
wemo:
  discovery: true
  static:
    - 192.168.111.31

#Sonoff
sonoff:
  username: !secret user_sonoff
  password: !secret pw_sonoff
switch:
  - platform: template
    switches:
      ewelink_virtual_switch:
        turn_on:
          service: switch.turn_on
        turn_off:
          service: switch.turn_off

climate:
  - platform: generic_thermostat
    name: Diggs
    unique_id: 20231842
    heater: light.diggs_heater
    target_sensor:
      sensor.diggs_temp

#Sengled
sengledapi:
  username: !secret sengled_username
  password: !secret sengled_password
  country: us
  wifi: true

#Google Integration
google_assistant:
  project_id: ha-daponderosa
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light

#Proxmox
proxmoxve:
  - host: 192.168.111.199
    verify_ssl: false
    username: !secret prox_username
    password: !secret prox_password
    realm: pve
    nodes:
      - node: pve
        vms:
          - 100
          - 1000
        containers:
          - 150
          - 160
          - 170
          
#proximity
proximity:
  da_ponderosa:
    ignored_zones:
      - meadowview
    devices:
      - device_tracker.jen
      - device_tracker.dad_iphone
      - device_tracker.ol_red_location_tracker
      - device_tracker.batmans_hot_dog
      - device_tracker.iphone_3
    tolerance: 100
    unit_of_measurement: mi
  castleview:
    ignored_zones:
      - kingsoopers
      - walmart
    devices:
      - device_tracker.batmans_hot_dog
      - device_tracker.iphone_3
    tolerance: 100
    unit_of_measurement: mi
  walmart:
    ignored_zones:
      - kingsoopers
      - CRMS
      - castleview
    devices:
      - device_tracker.jen
      - device_tracker.dad_iphone
      - device_tracker.ol_red_location_tracker
      - device_tracker.batmans_hot_dog
      - device_tracker.iphone_3
    tolerance: 100
    unit_of_measurement: mi
  

